---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: cg-master
data:
  SPRING_PROFILES_ACTIVE: master
  SERVER_PORT: "8082"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  AUTH_API_URL: http://auth-service:8180
  JWT_SECRET: "my-super-secret-dev-key-32-chars-long-12345678"
  JWT_EXPIRATION: "3600000"
