---
apiVersion: v1
kind: ConfigMap
metadata:
  name: form-service-config
  namespace: cg-master
data:
  SPRING_PROFILES_ACTIVE: master
  SERVER_PORT: "8086"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/circleguard_form
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
