---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-service
  namespace: cg-dev
  labels:
    app: form-service
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: form-service
  template:
    metadata:
      labels:
        app: form-service
    spec:
      containers:
        - name: form-service
          image: circleguard/form-service:dev
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: form-service-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 60
            periodSeconds: 30
