---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: cg-master
spec:
  selector:
    app: gateway-service
  ports:
    - port: 8087
      targetPort: 8087
  type: ClusterIP
