---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: cg-stage
spec:
  selector:
    app: identity-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
