---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: cg-stage
data:
  SPRING_PROFILES_ACTIVE: stage
  SERVER_PORT: "8180"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/circleguard_auth
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_LDAP_URLS: ldap://openldap-service:389
  SPRING_LDAP_BASE: dc=circleguard,dc=edu
  SPRING_LDAP_USERNAME: cn=admin,dc=circleguard,dc=edu
  JWT_SECRET: "my-super-secret-dev-key-32-chars-long-12345678"
  JWT_EXPIRATION: "3600000"
