---
# ConfigMap para gateway-service — ambiente dev
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
  namespace: cg-dev
data:
  SPRING_PROFILES_ACTIVE: dev
  SERVER_PORT: "8087"
  SPRING_DATA_REDIS_HOST: redis-service
  SPRING_DATA_REDIS_PORT: "6379"
  JWT_SECRET: "my-super-secret-dev-key-32-chars-long-12345678"
  AUTH_API_URL: http://auth-service:8180
