---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promotion-service-config
  namespace: cg-master
data:
  SPRING_PROFILES_ACTIVE: master
  SERVER_PORT: "8088"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/circleguard_promotion
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_NEO4J_URI: bolt://neo4j-service:7687
  SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  SPRING_DATA_REDIS_HOST: redis-service
  JWT_SECRET: "my-super-secret-dev-key-32-chars-long-12345678"
  JWT_EXPIRATION: "3600000"
