---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: cg-dev
  labels:
    app: notification-service
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: circleguard/notification-service:dev
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: notification-service-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 30
