apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/circleguard_auth"
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_DATASOURCE_PASSWORD: "password"
  SPRING_LDAP_URLS: "ldap://openldap:389"
  SPRING_LDAP_BASE: "dc=circleguard,dc=edu"
  SPRING_LDAP_USERNAME: "cn=admin,dc=circleguard,dc=edu"
  SPRING_LDAP_PASSWORD: "admin"
  JWT_SECRET: "my-super-secret-dev-key-32-chars-long-12345678"
  JWT_EXPIRATION: "3600000"
  QR_SECRET: "my-qr-secret-key-for-dev-1234567890"
  QR_EXPIRATION: "300"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: juan0073/circleguard-auth-service:latest
          ports:
            - containerPort: 8180
          envFrom:
            - configMapRef:
                name: auth-service-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8180
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8180
            initialDelaySeconds: 60
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 8180
      targetPort: 8180
  type: ClusterIP
