---
# ConfigMap para identity-service — ambiente dev
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-service-config
  namespace: cg-dev
data:
  SPRING_PROFILES_ACTIVE: dev
  SERVER_PORT: "8083"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/circleguard_identity
  SPRING_DATASOURCE_USERNAME: admin
  JWT_SECRET: "my-super-secret-dev-key-32-chars-long-12345678"
  JWT_EXPIRATION: "3600000"
